/**
 * Hevy's built-in (default) exercise library.
 *
 * The private app API exposes NO endpoint that lists the full exercise
 * library — the app ships it bundled, and the public developer
 * `/v1/exercise_templates` endpoint requires a Pro-only API key. So this list
 * is bundled instead. Every entry uses Hevy's canonical 8-character template id
 * (e.g. "79D0BB3A"), so the ids are usable directly when building routines.
 *
 * Sources, cross-verified against each other (all overlapping ids matched):
 *  - the official hevyapp/hevy-gpt exercise list (100 exercises), and
 *  - default exercises observed live in the social feed + workout history.
 * Entries with only id+title had no live metadata available to enrich them.
 *
 * This is a seed: HevyClient.getExerciseCatalog() unions it with your custom
 * exercises and any defaults seen in your routines/history/feed, so coverage
 * grows beyond this list at runtime.
 */
import type { CatalogEntry } from "./match.js";

export const DEFAULT_EXERCISES: CatalogEntry[] = [
  {"exercise_template_id":"A69FF221","title":"Arnold Press (Dumbbell)"},
  {"exercise_template_id":"A05C064D","title":"Back Extension (Machine)"},
  {"exercise_template_id":"DDB29047","title":"Behind the Back Bicep Wrist Curl (Barbell)","muscle_group":"forearms","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"2DBCA395","title":"Behind the Back Curl (Cable)","muscle_group":"biceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"35B51B87","title":"Bench Press - Close Grip (Barbell)","muscle_group":"triceps","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"79D0BB3A","title":"Bench Press (Barbell)","muscle_group":"chest","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"3601968B","title":"Bench Press (Dumbbell)"},
  {"exercise_template_id":"0FBF7195","title":"Bench Press (Smith Machine)","muscle_group":"chest","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"55E6546F","title":"Bent Over Row (Barbell)"},
  {"exercise_template_id":"23E92538","title":"Bent Over Row (Dumbbell)"},
  {"exercise_template_id":"A5AC6449","title":"Bicep Curl (Barbell)"},
  {"exercise_template_id":"37FCC2BB","title":"Bicep Curl (Dumbbell)","muscle_group":"biceps","equipment_category":"dumbbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"594450D2","title":"Bicycle Crunch Raised Legs","muscle_group":"abdominals","equipment_category":"none","exercise_type":"reps_only"},
  {"exercise_template_id":"BB792A36","title":"Burpee"},
  {"exercise_template_id":"9DCE2D64","title":"Butterfly (Pec Deck)","muscle_group":"chest","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"23A48484","title":"Cable Crunch","muscle_group":"abdominals","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"651F844C","title":"Cable Fly Crossovers","muscle_group":"chest","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"47B9DF13","title":"Calf Extension (Machine)","muscle_group":"calves","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"6FCD7755","title":"Chest Dip"},
  {"exercise_template_id":"29472BE1","title":"Chest Dip (Weighted)","muscle_group":"chest","equipment_category":"machine","exercise_type":"bodyweight_reps"},
  {"exercise_template_id":"12017185","title":"Chest Fly (Dumbbell)"},
  {"exercise_template_id":"78683336","title":"Chest Fly (Machine)","muscle_group":"chest","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"7EB3F7C3","title":"Chest Press (Machine)","muscle_group":"chest","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"29083183","title":"Chin Up","muscle_group":"lats","equipment_category":"machine","exercise_type":"reps_only"},
  {"exercise_template_id":"724CDE60","title":"Concentration Curl"},
  {"exercise_template_id":"DCF3B31B","title":"Crunch"},
  {"exercise_template_id":"EB43ADD4","title":"Crunch (Machine)"},
  {"exercise_template_id":"B9380898","title":"Dead Hang","muscle_group":"upper_back","equipment_category":"none","exercise_type":"duration"},
  {"exercise_template_id":"C6272009","title":"Deadlift (Barbell)"},
  {"exercise_template_id":"5F4E6DD3","title":"Deadlift (Dumbbell)"},
  {"exercise_template_id":"B923B230","title":"Deadlift (Trap bar)","muscle_group":"glutes","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"DA0F0470","title":"Decline Bench Press (Barbell)"},
  {"exercise_template_id":"18487FA7","title":"Decline Bench Press (Dumbbell)"},
  {"exercise_template_id":"FAF31231","title":"Decline Bench Press (Machine)"},
  {"exercise_template_id":"BC10A922","title":"Decline Crunch"},
  {"exercise_template_id":"C43825EA","title":"Decline Push Up"},
  {"exercise_template_id":"F1E57334","title":"Dumbbell Row"},
  {"exercise_template_id":"3303376C","title":"Elliptical Trainer"},
  {"exercise_template_id":"2FA77B28","title":"Flutter Kicks","muscle_group":"abdominals","equipment_category":"none","exercise_type":"reps_only"},
  {"exercise_template_id":"0E608350","title":"Front Lever Hold","muscle_group":"full_body","equipment_category":"none","exercise_type":"duration"},
  {"exercise_template_id":"5046D0A9","title":"Front Squat"},
  {"exercise_template_id":"CDA23948","title":"Glute Bridge"},
  {"exercise_template_id":"CBA02382","title":"Glute Kickback (Machine)"},
  {"exercise_template_id":"987234AB","title":"Glute Kickback on Floor"},
  {"exercise_template_id":"3D0C7C75","title":"Goblet Squat"},
  {"exercise_template_id":"4180C405","title":"Good Morning (Barbell)"},
  {"exercise_template_id":"1E42FD5F","title":"Hack Squat (Machine)","muscle_group":"quadriceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"36E8F14E","title":"Hammer Curl (Cable)","muscle_group":"biceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"7E3BC8B6","title":"Hammer Curl (Dumbbell)","muscle_group":"biceps","equipment_category":"dumbbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"08590920","title":"Hanging Knee Raise"},
  {"exercise_template_id":"F8356514","title":"Hanging Leg Raise","muscle_group":"abdominals","equipment_category":"none","exercise_type":"reps_only"},
  {"exercise_template_id":"567FB505","title":"Heel Taps","muscle_group":"abdominals","equipment_category":"none","exercise_type":"reps_only"},
  {"exercise_template_id":"F4B4C6EE","title":"Hip Abduction (Machine)","muscle_group":"abductors","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"8BEBFED6","title":"Hip Adduction (Machine)","muscle_group":"adductors","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"92B8C7E1","title":"Hip Thrust"},
  {"exercise_template_id":"D57C2EC7","title":"Hip Thrust (Barbell)"},
  {"exercise_template_id":"68CE0B9B","title":"Hip Thrust (Machine)"},
  {"exercise_template_id":"50DFDFAB","title":"Incline Bench Press (Barbell)"},
  {"exercise_template_id":"07B38369","title":"Incline Bench Press (Dumbbell)","muscle_group":"chest","equipment_category":"dumbbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"3A6FA3D1","title":"Incline Bench Press (Smith Machine)","muscle_group":"chest","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"D3E2AB55","title":"Incline Chest Fly (Dumbbell)"},
  {"exercise_template_id":"FBF92739","title":"Incline Chest Press (Machine)"},
  {"exercise_template_id":"BC3492DA","title":"Iso-Lateral High Row (Machine)","muscle_group":"lats","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"91FAFBA3","title":"Iso-Lateral Low Row"},
  {"exercise_template_id":"AA1EB7D8","title":"Iso-Lateral Row (Machine)"},
  {"exercise_template_id":"040BA2E3","title":"Jump Rope"},
  {"exercise_template_id":"991833C2","title":"Jumping Jack"},
  {"exercise_template_id":"5CC07A1F","title":"Jumping Lunge"},
  {"exercise_template_id":"F99C211D","title":"Kettlebell Clean"},
  {"exercise_template_id":"4E239ED8","title":"Kettlebell Curl"},
  {"exercise_template_id":"A127DA73","title":"Kettlebell Goblet Squat"},
  {"exercise_template_id":"9B13BA4B","title":"Kettlebell High Pull"},
  {"exercise_template_id":"6433CD93","title":"Kettlebell Shoulder Press"},
  {"exercise_template_id":"89304423","title":"Kettlebell Snatch"},
  {"exercise_template_id":"F8A0FCCA","title":"Kettlebell Swing"},
  {"exercise_template_id":"98237BA2","title":"Knee Raise Parallel Bars"},
  {"exercise_template_id":"B74A95BB","title":"Kneeling Push Up"},
  {"exercise_template_id":"4E5257DE","title":"Lat Pulldown - Close Grip (Cable)","muscle_group":"lats","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"6A6C31A5","title":"Lat Pulldown (Cable)","muscle_group":"lats","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"473CF5B8","title":"Lat Pulldown (Machine)"},
  {"exercise_template_id":"BE289E45","title":"Lateral Raise (Cable)","muscle_group":"shoulders","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"422B08F1","title":"Lateral Raise (Dumbbell)"},
  {"exercise_template_id":"D5D0354D","title":"Lateral Raise (Machine)","muscle_group":"shoulders","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"75A4F6C4","title":"Leg Extension (Machine)","muscle_group":"quadriceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"C7973E0E","title":"Leg Press (Machine)","muscle_group":"quadriceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"0EB695C9","title":"Leg Press Horizontal (Machine)","muscle_group":"quadriceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"0482DA98","title":"Leg Raise Parallel Bars"},
  {"exercise_template_id":"5E1A7777","title":"Lunge"},
  {"exercise_template_id":"B537D09F","title":"Lunge (Dumbbell)"},
  {"exercise_template_id":"9F9C164B","title":"Muscle Up","muscle_group":"full_body","equipment_category":"machine","exercise_type":"reps_only"},
  {"exercise_template_id":"7B8D84E8","title":"Overhead Press (Barbell)"},
  {"exercise_template_id":"6AC96645","title":"Overhead Press (Dumbbell)"},
  {"exercise_template_id":"B5EFBF9C","title":"Overhead Triceps Extension (Cable)","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"018ADC12","title":"Pendlay Row (Barbell)"},
  {"exercise_template_id":"0EFE8162","title":"Pike Pushup"},
  {"exercise_template_id":"C6C9B8A0","title":"Plank","muscle_group":"abdominals","equipment_category":"none","exercise_type":"duration"},
  {"exercise_template_id":"4F942934","title":"Preacher Curl (Barbell)","muscle_group":"biceps","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"FAB6EB2F","title":"Preacher Curl (Dumbbell)","muscle_group":"biceps","equipment_category":"dumbbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"1E9A6B8E","title":"Preacher Curl (Machine)","muscle_group":"biceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"1B2B1E7C","title":"Pull Up","muscle_group":"lats","equipment_category":"machine","exercise_type":"reps_only"},
  {"exercise_template_id":"729237D1","title":"Pull Up (Weighted)","muscle_group":"lats","equipment_category":"machine","exercise_type":"bodyweight_reps"},
  {"exercise_template_id":"392887AA","title":"Push Up","muscle_group":"chest","equipment_category":"none","exercise_type":"reps_only"},
  {"exercise_template_id":"FE389074","title":"Rack Pull"},
  {"exercise_template_id":"D8281C62","title":"Rear Delt Reverse Fly (Machine)","muscle_group":"shoulders","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"112FC6B7","title":"Reverse Curl (Barbell)","muscle_group":"biceps","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"2B4B7310","title":"Romanian Deadlift (Barbell)"},
  {"exercise_template_id":"72CFFAD5","title":"Romanian Deadlift (Dumbbell)"},
  {"exercise_template_id":"0222DB42","title":"Rowing Machine"},
  {"exercise_template_id":"2982AA23","title":"Russian Twist (Weighted)","muscle_group":"abdominals","equipment_category":"plate","exercise_type":"weight_reps"},
  {"exercise_template_id":"0393F233","title":"Seated Cable Row - V Grip (Cable)","muscle_group":"upper_back","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"062AB91A","title":"Seated Calf Raise"},
  {"exercise_template_id":"5122E7D9","title":"Seated Dip Machine","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"8BAB2735","title":"Seated Incline Curl (Dumbbell)","muscle_group":"biceps","equipment_category":"dumbbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"11A123F3","title":"Seated Leg Curl (Machine)","muscle_group":"hamstrings","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"91AF29E0","title":"Seated Overhead Press (Barbell)"},
  {"exercise_template_id":"9930DF71","title":"Seated Overhead Press (Dumbbell)"},
  {"exercise_template_id":"1DF4A847","title":"Seated Row (Machine)","muscle_group":"upper_back","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"9237BAD1","title":"Seated Shoulder Press (Machine)","muscle_group":"shoulders","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"878CD1D0","title":"Shoulder Press (Dumbbell)","muscle_group":"shoulders","equipment_category":"dumbbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"059E835D","title":"Shoulder Press (Machine Plates)","muscle_group":"shoulders","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"ABEC557F","title":"Shrug (Dumbbell)"},
  {"exercise_template_id":"DE68C825","title":"Single Arm Lateral Raise (Cable)","muscle_group":"shoulders","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"552AB030","title":"Single Arm Triceps Pushdown (Cable)","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"022DF610","title":"Sit Up"},
  {"exercise_template_id":"68F8A292","title":"Skullcrusher (Dumbbell)"},
  {"exercise_template_id":"D04AC939","title":"Squat (Barbell)","muscle_group":"quadriceps","equipment_category":"barbell","exercise_type":"weight_reps"},
  {"exercise_template_id":"9694DA61","title":"Squat (Bodyweight)"},
  {"exercise_template_id":"06745E58","title":"Standing Calf Raise"},
  {"exercise_template_id":"E05C2C38","title":"Standing Calf Raise (Machine)","muscle_group":"calves","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"AA52E8D2","title":"Standing Calf Raise (Smith)","muscle_group":"calves","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"073032BB","title":"Standing Military Press (Barbell)"},
  {"exercise_template_id":"527DA061","title":"Stretching","muscle_group":"other","equipment_category":"none","exercise_type":"duration"},
  {"exercise_template_id":"75BAC5C3","title":"Toe Touch","muscle_group":"abdominals","equipment_category":"none","exercise_type":"reps_only"},
  {"exercise_template_id":"243710DE","title":"Treadmill","muscle_group":"cardio","equipment_category":"machine","exercise_type":"distance_duration"},
  {"exercise_template_id":"28BB4A95","title":"Triceps Dip"},
  {"exercise_template_id":"21310F5F","title":"Triceps Extension (Cable)","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"3765684D","title":"Triceps Extension (Dumbbell)"},
  {"exercise_template_id":"3092FADD","title":"Triceps Extension (Machine)","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"6127A3AD","title":"Triceps Kickback (Dumbbell)"},
  {"exercise_template_id":"93A552C6","title":"Triceps Pushdown","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
  {"exercise_template_id":"94B7239B","title":"Triceps Rope Pushdown","muscle_group":"triceps","equipment_category":"machine","exercise_type":"weight_reps"},
].map((e) => ({ ...e, is_custom: false }));
